---
title: "Schedule"
description: |
 Schedule and course materials for Statistical Programming Paradigms and Workflows (JHSPH Biostatistics 140.777 Fall 2023).
tbl-colwidths: [15,10, 55, 20]
engine: knitr
---

## Schedule and course materials

For Qmd files, go to the [course GitHub repository](https://github.com/stephaniehicks/jhustatprogramming2023) and navigate the directories, or best of all to clone the repo and navigate within RStudio.

::: column-page
| Week         | Dates   | Topics | Projects  |
|---|---|---|---|---|
| **Module 1** | | **Statistical programming at the command-line**  | |
| | | |
| Week 1 | Oct 26  | Course introduction \[[syllabus](syllabus.qmd)\] | `r emojifont::emoji('palm_tree')` Project 1 \[[html](projects/2023-10-26-project-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/projects/2023-10-26-project-1/index.qmd)\] |
| | | Building websites with `quarto` \[[html](posts/2023-10-26-build-website/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-10-26-build-website/index.qmd)\] | | 
| | | | |
| | | | |
| Week 2 | Oct 31  | Introduction to the command-line \[[html](posts/2023-10-31-command-line-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-10-31-command-line-part-1/index.qmd)\] |   |
| | | | | 
| | Nov 2  | More advanced command-line tools \[[html](posts/2023-11-02-command-line-part-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-11-02-command-line-part-2/index.qmd)\]  | |
| | |  | | 
| Week 3  | Nov 7 |  Version control (git) \[[html](posts/2023-11-07-version-control-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-11-07-version-control-part-1/index.qmd)\] | `r emojifont::emoji('palm_tree')` Project 2 \[[html](projects/2023-11-07-project-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/projects/2023-11-07-project-2/index.qmd)\] | 
| | | |                            | | | |
| | Nov 9 | Version control (GitHub) \[[html](posts/2023-11-09-version-control-part-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-11-09-version-control-part-2/index.qmd)\]  |   |
| | | | | 
| | Nov 10 | | `r emojifont::emoji('fallen_leaf')` Project 1 due | 
| | | | | 
| **Module 2** |         | **R software development** | |  
| | | |
| Week 4 | Nov 14  | Object Oriented Programming \[[html](posts/2023-11-14-oop-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-11-14-oop-part-1/index.qmd)\] |  | 
| | | | |
| | Nov 16 | More OOP | | 
| | | | | 
| Week 5   | Nov 21 | R package software development \[[html](posts/2023-11-21-r-pkg-dev/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2023/blob/main/posts/2023-11-21-r-pkg-dev/index.qmd)\] | | 
| | | | | 
| |  Nov 23 | `r emojifont::emoji('turkey')` No lecture, enjoy the break! | | 
| | | | |
| | Nov 24 | |   |
| | | | |
| **Module 3** |         | **Advanced programming paradigms** | |  
| | | | | 
| Week 6 | Nov 28 | Functional programming with `purrr` | `r emojifont::emoji('fallen_leaf')` Project 2 due  <br /> `r emojifont::emoji('palm_tree')` Project 3    |
| | | | | 
| | Nov 30  | Project management with `targets`  | |
| | | Package website with `pkgdown`  | |
| | | | | 
| Week 7 | Dec 5  | Retrieving data from APIs  | | 
| |  |  | |
| | | |
| | Dec 7 | Relational databases and SQL basics | | 
| | | |
| **Module 4** |  | **Interactive web apps and dashboards**  | | 
| | | |
|  Week 8 | Dec 12  |  Building dashboards with `flexdashboard` and `shinydashboard`  | `r emojifont::emoji('fallen_leaf')` Project 3 due  <br />  `r emojifont::emoji('palm_tree')` Project 4 | 
| | | |
| | Dec 14  | Scraping data from the web with `rvest` |  | 
| | | |
| **Module 5** |  | **Dealing with "big" data**  | | 
| | | |
| Week 9       | Dec 19  | Strategies for dealing with large data |  | 
| | | |
| | Dec 21 | `r emojifont::emoji('snowflake')` Class is canceled | | 
| | | |
| | Dec 22  | | `r emojifont::emoji('fallen_leaf')` Project 4 due  |
:::


